import type { AiConceptItem, AiConceptSection, AiConceptSectionKind } from "./types.ts";
import { verification } from "./repo-categories.ts";

const TITLE_BY_KIND: Record<AiConceptSectionKind, { zh: string; en: string }> = {
  definition: { zh: "定义", en: "Definition" },
  function: { zh: "作用", en: "Functions" },
  scenario: { zh: "场景", en: "Use Cases" },
  relation: { zh: "关系", en: "Relationships" },
};

function section(
  kind: AiConceptSectionKind,
  zh: string,
  en: string,
  sourceUrl: string,
  reason: string,
): AiConceptSection {
  return {
    kind,
    title: TITLE_BY_KIND[kind],
    content: { zh, en },
    verification: verification(sourceUrl, reason),
  };
}

function concept(input: AiConceptItem): AiConceptItem {
  return input;
}

export const AI_CONCEPTS: AiConceptItem[] = [
  concept({
    id: "agent",
    tab: "agent-system",
    title: { zh: "Agent（智能代理）", en: "Agent" },
    subtitle: { zh: "可自主规划与执行的 AI 实体", en: "AI entity that plans and executes autonomously" },
    support_level: "official",
    verification: verification("https://docs.anthropic.com/en/docs/claude-code/overview", "基于官方 Agentic coding 产品文档语义。"),
    sections: [
      section(
        "definition",
        "Agent 是围绕目标执行的自主系统：能理解任务、拆解步骤、调用工具并根据反馈迭代。",
        "An agent is a goal-driven autonomous system that plans tasks, calls tools, and iterates with feedback.",
        "https://docs.anthropic.com/en/docs/claude-code/overview",
        "官方定义语义。",
      ),
      section(
        "function",
        "将“问答式模型”升级为“可执行工作流”的生产单元，缩短从需求到交付的路径。",
        "It turns LLM interaction into executable workflows and shortens the path from intent to delivery.",
        "https://developers.openai.com/codex/cli",
        "官方 CLI Agentic 工作流语义。",
      ),
      section(
        "scenario",
        "代码改造、批量测试、变更审查、文档维护等需要多步执行与回路反馈的任务。",
        "Code migration, batch testing, review loops, and documentation maintenance.",
        "https://developers.openai.com/codex/cli/reference",
        "官方命令工作流覆盖。",
      ),
      section(
        "relation",
        "Agent 通常通过 MCP 使用外部能力，通过 Skills 复用任务模板，并可通过 A2A 协同。",
        "Agents typically use MCP for tools, Skills for reusable patterns, and A2A for inter-agent collaboration.",
        "https://modelcontextprotocol.io/introduction",
        "协议关系说明。",
      ),
    ],
  }),
  concept({
    id: "sub-agent",
    tab: "agent-system",
    title: { zh: "Sub-Agent（子代理）", en: "Sub-Agent" },
    subtitle: { zh: "面向子任务的并行执行单元", en: "Parallel execution unit for sub-tasks" },
    support_level: "official",
    verification: verification("https://developers.openai.com/codex/cli/reference", "官方子命令与会话管理语义可映射子任务执行。"),
    sections: [
      section(
        "definition",
        "Sub-Agent 是主 Agent 派生的临时执行体，聚焦单一子目标。",
        "A sub-agent is a temporary worker spawned by a parent agent for a focused sub-goal.",
        "https://developers.openai.com/codex/cli/reference",
        "官方会话与任务拆解语义。",
      ),
      section(
        "function",
        "将复杂任务并行化，降低上下文冲突，提高执行吞吐。",
        "It parallelizes complex tasks, reduces context conflicts, and increases throughput.",
        "https://docs.anthropic.com/en/docs/claude-code/overview",
        "官方 Agent 流程实践。",
      ),
      section(
        "scenario",
        "多文件重构、跨模块排障、并行测试与多文档抽取。",
        "Multi-file refactoring, cross-module debugging, parallel tests, and multi-doc extraction.",
        "https://docs.anthropic.com/en/docs/claude-code/overview",
        "官方场景实践。",
      ),
      section(
        "relation",
        "Sub-Agent 与 Workflow 编排、MCP 工具调用和主 Agent 审核形成闭环。",
        "Sub-agents operate within workflow orchestration and report back to the parent review loop.",
        "https://modelcontextprotocol.io/introduction",
        "协议关系约束。",
      ),
    ],
  }),
  concept({
    id: "skills",
    tab: "agent-system",
    title: { zh: "Skills（技能包）", en: "Skills" },
    subtitle: { zh: "可复用的任务知识模块", en: "Reusable task knowledge modules" },
    support_level: "official",
    verification: verification("https://docs.anthropic.com/en/docs/claude-code/skills", "Claude Skills 官方文档可验证。"),
    sections: [
      section(
        "definition",
        "Skill 由结构化说明（如 SKILL.md）定义触发条件、步骤和输出标准。",
        "A skill defines trigger conditions, steps, and expected outputs, usually via SKILL.md.",
        "https://docs.anthropic.com/en/docs/claude-code/skills",
        "官方定义。",
      ),
      section(
        "function",
        "将团队方法论沉淀为可调用资产，降低交付波动。",
        "It operationalizes team know-how into reusable execution assets.",
        "https://developers.openai.com/codex/prompting",
        "Agent Skills 官方语义。",
      ),
      section(
        "scenario",
        "安全审计、发布检查、数据库迁移、测试基线复核等标准化任务。",
        "Security reviews, release checks, DB migrations, and test baseline validation.",
        "https://developers.openai.com/codex/prompting",
        "官方用例语义。",
      ),
      section(
        "relation",
        "Skills 与 Prompt/Workflow 联动，并可通过 MCP 扩展工具能力。",
        "Skills integrate with prompts/workflows and can extend through MCP tools.",
        "https://modelcontextprotocol.io/introduction",
        "协议与能力关系。",
      ),
    ],
  }),
  concept({
    id: "mcp",
    tab: "protocols",
    title: { zh: "MCP（Model Context Protocol）", en: "MCP (Model Context Protocol)" },
    subtitle: { zh: "Agent 与工具的标准接口", en: "Standard interface between agents and tools" },
    support_level: "official",
    verification: verification("https://modelcontextprotocol.io/introduction", "MCP 官方介绍可访问。"),
    sections: [
      section(
        "definition",
        "MCP 定义模型如何安全地发现并调用外部工具和数据源。",
        "MCP defines how models discover and call external tools and data sources safely.",
        "https://modelcontextprotocol.io/introduction",
        "官方定义。",
      ),
      section(
        "function",
        "统一工具接入协议，减少每个 Agent 单独适配的工程成本。",
        "It standardizes tool integration and reduces bespoke adapter costs.",
        "https://github.com/modelcontextprotocol/servers",
        "官方参考实现。",
      ),
      section(
        "scenario",
        "文件读写、浏览器自动化、搜索检索、数据库查询、企业系统连接。",
        "File operations, browser automation, search, DB querying, and enterprise integrations.",
        "https://github.com/modelcontextprotocol/servers",
        "官方服务器生态。",
      ),
      section(
        "relation",
        "MCP 是 Agent 落地“可执行能力”的关键基础设施。",
        "MCP is foundational infrastructure for executable agent capabilities.",
        "https://modelcontextprotocol.io/introduction",
        "官方关系语义。",
      ),
    ],
  }),
  concept({
    id: "a2a",
    tab: "protocols",
    title: { zh: "A2A（Agent2Agent）", en: "A2A (Agent2Agent)" },
    subtitle: { zh: "Agent 间协作协议", en: "Collaboration protocol for inter-agent communication" },
    support_level: "official",
    verification: verification("https://github.com/google-a2a/A2A", "A2A 官方仓库可访问。", "official_repo"),
    sections: [
      section(
        "definition",
        "A2A 用于定义 Agent 之间的任务交接、状态同步和协作接口。",
        "A2A defines task handoff, state sync, and collaboration interfaces between agents.",
        "https://github.com/google-a2a/A2A",
        "官方仓库说明。",
      ),
      section(
        "function",
        "跨组织与跨框架的 Agent 协作可通过统一协议降低集成成本。",
        "It lowers integration cost for cross-team and cross-framework agent collaboration.",
        "https://cloud.google.com/blog/products/ai-machine-learning/agent2agent-protocol-is-getting-an-upgrade",
        "官方升级公告语义。",
      ),
      section(
        "scenario",
        "多 Agent 服务编排、跨系统审批流、跨域研究与客服协作。",
        "Multi-agent orchestration, cross-system approval workflows, and distributed support operations.",
        "https://developers.googleblog.com/google-cloud-donates-a2a-to-linux-foundation/",
        "官方生态推进。",
      ),
      section(
        "relation",
        "A2A 侧重 Agent-Agent 协同，MCP 侧重 Agent-Tool 调用，两者互补。",
        "A2A focuses on agent-to-agent collaboration, while MCP focuses on agent-to-tool execution.",
        "https://modelcontextprotocol.io/introduction",
        "协议边界关系。",
      ),
    ],
  }),
  concept({
    id: "lsp",
    tab: "protocols",
    title: { zh: "LSP（语言服务器协议）", en: "LSP (Language Server Protocol)" },
    subtitle: { zh: "代码语义分析标准接口", en: "Standard interface for code semantic analysis" },
    support_level: "official",
    verification: verification("https://microsoft.github.io/language-server-protocol/", "LSP 官方规范站点可访问。", "official_repo"),
    sections: [
      section(
        "definition",
        "LSP 规定编辑器与语言分析服务之间的消息格式和能力协商。",
        "LSP defines message formats and capability negotiation between editors and language services.",
        "https://microsoft.github.io/language-server-protocol/",
        "官方定义。",
      ),
      section(
        "function",
        "为 Agent 提供跳转定义、引用查找、诊断和重构等结构化能力。",
        "It gives agents structured capabilities like go-to-definition, references, diagnostics, and refactoring.",
        "https://microsoft.github.io/language-server-protocol/",
        "官方能力集。",
      ),
      section(
        "scenario",
        "大型代码库理解、精准改动定位、自动修复与质量审查。",
        "Large codebase comprehension, precise edits, automated fixes, and quality review.",
        "https://developers.openai.com/codex/cli",
        "官方编码助手场景。",
      ),
      section(
        "relation",
        "LSP 可以被封装进 MCP Server，供不同 Agent 统一调用。",
        "LSP can be exposed via MCP servers so different agents can consume it consistently.",
        "https://github.com/modelcontextprotocol/servers",
        "官方服务器生态关系。",
      ),
    ],
  }),
  concept({
    id: "rag",
    tab: "methods",
    title: { zh: "RAG（检索增强生成）", en: "RAG (Retrieval-Augmented Generation)" },
    subtitle: { zh: "以外部知识提升准确性", en: "Improving accuracy with external knowledge" },
    support_level: "official",
    verification: verification("https://developers.openai.com/api", "官方检索增强指南语义。"),
    sections: [
      section(
        "definition",
        "RAG 在生成前先检索高相关资料，再把证据注入上下文。",
        "RAG retrieves relevant evidence first, then injects it into model context before generation.",
        "https://developers.openai.com/api",
        "官方指南。",
      ),
      section(
        "function",
        "降低幻觉并提升可追溯性，适合时效性和专业性较强的任务。",
        "It reduces hallucination and improves traceability for time-sensitive and domain tasks.",
        "https://developers.openai.com/api",
        "官方能力说明。",
      ),
      section(
        "scenario",
        "企业知识库问答、法规与合规检索、代码库上下文补全。",
        "Enterprise Q&A, compliance retrieval, and codebase context augmentation.",
        "https://modelcontextprotocol.io/introduction",
        "协议化检索场景。",
      ),
      section(
        "relation",
        "RAG 常作为 Workflow 中的前置步骤，再由 Agent 执行决策和操作。",
        "RAG often runs as a workflow pre-step before agent decision and action.",
        "https://developers.openai.com/codex/cli",
        "Agent 工作流关系。",
      ),
    ],
  }),
  concept({
    id: "workflow",
    tab: "methods",
    title: { zh: "Workflow（工作流编排）", en: "Workflow Orchestration" },
    subtitle: { zh: "将复杂任务拆分为可执行步骤", en: "Turning complex goals into executable steps" },
    support_level: "official",
    verification: verification("https://developers.openai.com/codex/cli/reference", "官方 CLI 任务执行语义可映射流程编排。"),
    sections: [
      section(
        "definition",
        "Workflow 是任务分解、顺序控制、重试和回滚规则的组合。",
        "Workflow combines task decomposition, sequencing, retry, and rollback policies.",
        "https://developers.openai.com/codex/cli/reference",
        "官方执行语义。",
      ),
      section(
        "function",
        "提高可观测性与可控性，避免“单轮提示词”导致的不可重复行为。",
        "It improves observability and repeatability versus one-shot prompt behaviors.",
        "https://docs.anthropic.com/en/docs/claude-code/overview",
        "官方实践语义。",
      ),
      section(
        "scenario",
        "需求分析 → 代码变更 → 测试验证 → 审查修复 → 输出发布说明。",
        "Requirements analysis → code changes → tests → review fixes → release notes.",
        "https://developers.openai.com/codex/cli",
        "官方编码流程场景。",
      ),
      section(
        "relation",
        "Workflow 通常由 Agent 执行，借助 Skills 复用策略并通过 MCP 调用工具。",
        "Workflows are executed by agents, reuse skills, and call tools through MCP.",
        "https://modelcontextprotocol.io/introduction",
        "能力协同关系。",
      ),
    ],
  }),
  concept({
    id: "eval-loop",
    tab: "methods",
    title: { zh: "Eval Loop（评测闭环）", en: "Eval Loop" },
    subtitle: { zh: "以指标驱动的持续优化流程", en: "Metric-driven continuous optimization loop" },
    support_level: "official",
    verification: verification("https://developers.openai.com/api", "官方评测指南语义。"),
    sections: [
      section(
        "definition",
        "Eval Loop 是“定义指标 → 执行样本 → 分析误差 → 回归验证”的循环。",
        "Eval loop is a cycle of metric definition, sampling, error analysis, and regression verification.",
        "https://developers.openai.com/api",
        "官方评测定义。",
      ),
      section(
        "function",
        "将模型与提示词迭代从主观判断转为数据驱动。",
        "It shifts model and prompt iteration from subjective judgment to data-driven control.",
        "https://developers.openai.com/api",
        "官方方法说明。",
      ),
      section(
        "scenario",
        "上线前回归、提示词版本对比、代理策略 A/B 试验。",
        "Pre-release regression, prompt version comparison, and agent strategy A/B tests.",
        "https://developers.openai.com/api",
        "官方应用场景。",
      ),
      section(
        "relation",
        "Eval Loop 与 Workflow/Skills 联动，构成“可测、可回滚”的工程化体系。",
        "Eval loops complement workflows and skills to create measurable and rollback-safe systems.",
        "https://developers.openai.com/codex/cli",
        "工程化关系。",
      ),
    ],
  }),
  concept({
    id: "model-routing",
    tab: "models",
    title: { zh: "Model Routing（模型路由）", en: "Model Routing" },
    subtitle: { zh: "按任务动态选择模型", en: "Dynamic model selection by task profile" },
    support_level: "official",
    verification: verification("https://developers.openai.com/api", "官方 API 与模型选择语义。"),
    sections: [
      section(
        "definition",
        "模型路由是根据任务复杂度、成本与时延自动选择模型的策略。",
        "Model routing chooses models based on task complexity, latency, and cost constraints.",
        "https://developers.openai.com/api",
        "官方 API 语义。",
      ),
      section(
        "function",
        "兼顾质量与成本，避免所有请求都落到高成本模型。",
        "It balances quality and cost instead of sending all requests to expensive models.",
        "https://docs.anthropic.com/en/api/messages",
        "官方模型调用语义。",
      ),
      section(
        "scenario",
        "摘要任务走轻量模型，复杂分析与代码审查走高能力模型。",
        "Use lighter models for summarization, stronger models for deep analysis and code review.",
        "https://ai.google.dev/gemini-api/docs",
        "官方模型调用语义。",
      ),
      section(
        "relation",
        "Model Routing 常与 Eval Loop 联动，通过离线评测更新路由策略。",
        "Model routing works with eval loops to evolve routing policies through offline benchmarks.",
        "https://developers.openai.com/api",
        "评测关系。",
      ),
    ],
  }),
  concept({
    id: "multimodal-reasoning",
    tab: "models",
    title: { zh: "Multimodal Reasoning（多模态推理）", en: "Multimodal Reasoning" },
    subtitle: { zh: "跨文本、图像、音视频的统一推理", en: "Unified reasoning across text, image, and media" },
    support_level: "official",
    verification: verification("https://developers.openai.com/api", "官方多模态能力入口。"),
    sections: [
      section(
        "definition",
        "多模态推理指模型在统一上下文中联合处理文本、图像、音视频信息。",
        "Multimodal reasoning jointly processes text, images, and media in one context.",
        "https://developers.openai.com/api",
        "官方能力入口。",
      ),
      section(
        "function",
        "减少跨工具切换，提高复杂任务信息整合效率。",
        "It reduces tool switching and improves information synthesis for complex tasks.",
        "https://ai.google.dev/gemini-api/docs",
        "官方多模态能力。",
      ),
      section(
        "scenario",
        "图表解释、截图排障、文档 + 代码联合分析、音视频摘要。",
        "Chart interpretation, screenshot debugging, mixed document-code analysis, and media summarization.",
        "https://docs.anthropic.com/en/api/messages",
        "官方 API 场景。",
      ),
      section(
        "relation",
        "多模态输入通常通过 MCP 工具链接入，并由 Workflow 统一编排。",
        "Multimodal inputs are often connected via MCP toolchains and orchestrated by workflows.",
        "https://modelcontextprotocol.io/introduction",
        "协议关系。",
      ),
    ],
  }),
  concept({
    id: "slm",
    tab: "models",
    title: { zh: "SLM（小型语言模型）", en: "SLM (Small Language Models)" },
    subtitle: { zh: "本地化与低成本推理选择", en: "Local and cost-efficient inference option" },
    support_level: "community",
    verification: verification(
      "https://huggingface.co/models",
      "主流平台模型生态参考（补充证据）。",
      "mainstream_platform",
    ),
    sections: [
      section(
        "definition",
        "SLM 通常参数规模更小，强调低时延、低成本与可本地部署。",
        "SLMs are smaller models optimized for low latency, low cost, and local deployment.",
        "https://huggingface.co/models",
        "主流平台生态信息。",
      ),
      section(
        "function",
        "适合高并发基础任务和数据不出域场景。",
        "They are suitable for high-throughput baseline tasks and data-sovereignty scenarios.",
        "https://huggingface.co/models",
        "主流平台生态信息。",
      ),
      section(
        "scenario",
        "日志分类、模板填充、规则化抽取、轻量 RAG 后处理。",
        "Log classification, templated generation, structured extraction, and light RAG post-processing.",
        "https://huggingface.co/models",
        "主流平台生态信息。",
      ),
      section(
        "relation",
        "SLM 常与大模型路由结合：高复杂度任务升级到强模型，常规任务留在本地。",
        "SLMs are often paired with model routing: escalate only complex tasks to stronger models.",
        "https://developers.openai.com/api",
        "模型路由关系。",
      ),
    ],
  }),
];
